version: "3.9"

services:
  doda_methane_generation:
    build: .
    container_name: DODA_methane_generation
    volumes:
      - type: bind
        source: ./models
        target: /app/models
      - type: bind
        source: ./output
        target: /app/output
      - type: bind
        source: ./datasets
        target: /app/datasets
      - type: bind
        source: ./image_log
        target: /app/image_log
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    stdin_open: true
    tty: true
